---
  - name: Need to create file
    hosts: CentOS
    become: true
    tasks:
      - name: Create one directory.
        ansible.builtin.file:
          path: /ansiblecreate
          state: directory
          mode: u=rw,g=r,o=r
      - name: Create one file in ansible
        ansible.builtin.file:
          path: /ansiblecreate/test.txt
          state: touch
          mode: u=rw,g=r,o=r
          
