---

- name: Installing kubectl in this machine
  hosts: ungrouped
  become: true
  tasks:
    - name: This command will install Kubectl using curl.
      ansible.builtin.shell:
        cmd: "{{item}}"     #curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"   
      loop:
        - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
